<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>36bff62b-a258-4be4-bb9c-3ab87250cf6c</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
		<PackageReference Include="Lamar" Version="15.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.19" />

		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.19" />

	</ItemGroup>

</Project>